CREATE TABLE users
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    safe_username    TEXT                                     NOT NULL UNIQUE,
    display_username TEXT                                     NOT NULL UNIQUE,
    password_hash    TEXT                                     NOT NULL
);
