CREATE TABLE roles
(
    id                       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    weight                   INTEGER                                  NOT NULL,
    safe_name                TEXT                                     NOT NULL UNIQUE,
    display_name             TEXT                                     NOT NULL,
    inherit_permissions_from INTEGER[]                                NOT NULL DEFAULT '{}',
    permissions              INTEGER[]                                NOT NULL DEFAULT '{}'
);

ALTER TABLE users
    ADD COLUMN superuser BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE users
    ADD COLUMN roles INTEGER[] NOT NULL DEFAULT '{}';
